lib/widgets/recents_alerts.dart
lib/widgets/recents_homeworks.dart

Fixed the scroll bug

---

lib/screens/welcome_screen.dart
lib/widgets/recents_alerts.dart
lib/widgets/recents_homeworks.dart

Overflow removed from alert, homework, and get started cards
Fixes  Issue #12

Overflow removed issue #12

---

android/app/build.gradle
android/app/google-services.json
android/build.gradle
lib/constants.dart
lib/main.dart
lib/screens/login_page.dart
lib/screens/onboarding_page.dart
lib/screens/signup_page.dart
lib/screens/welcome_screen.dart
lib/services/auth_error_msg_toast.dart
lib/services/authentication.dart
lib/widgets/auth_canvas.dart
lib/widgets/auth_input_form_field.dart
lib/widgets/login_form.dart
lib/widgets/onboarding_canvas_design.dart
lib/widgets/signup_form.dart
pubspec.lock
pubspec.yaml

This integrates the _Firebase Authentication_ services to the application by adding `Onboarding`, `Login`, and `Signup` Pages.
**Following tasks accomplished:** 
- Adds `Login`, `Signup`, and `Onboarding` Pages.
- Implements designs given by @purnima143
- Fixes #11, #14 and #21

Adds Authentication Services

---

.all-contributorsrc
README.md
lib/screens/home_screen.dart
lib/screens/homework_screen.dart
lib/screens/welcome_screen.dart
lib/widgets/bottom_navigation.dart
lib/widgets/recents_alerts.dart
lib/widgets/recents_homeworks.dart

Fixes #7 
- Created homework_screen.dart
- Made View all a button, to push navigator to HomeworkScreen

Created homework_screen.dart

---

lib/screens/home_screen.dart
lib/widgets/bottom_navigation.dart

- Fixes #26 
Please check and tell me if anything else is needed.

Bug Fix navbar missing

---

android/app/build.gradle
lib/main.dart
lib/services/authentication.dart
lib/widgets/login_form.dart
lib/widgets/signup_form.dart

**Following Tasks Accomplished:**
- Adds Entry Point Handling Service (along with persistent signup/login)
- Modifies `FirebaseAuthEaxception` Handling Services
- Modifies Email Validator of Login/SignUp forms
- Adds `Name` of the user to Profile Data
- Removes unnecessary code from `app/build.gradle`
- Fixes #29

Adds Entry Point Handling Service and Modifies Authentication Error Handling

---

lib/widgets/login_form.dart

Fixed Issue#33

---

lib/utils/bottom_navbar_tabs.dart
lib/widgets/animated_nav_bar.dart
lib/widgets/bottom_navigation.dart

This adds an Animated Bottom Navigation Bar.
Fixes #37.

Adds Animated Bottom Navigation Bar

---

lib/main.dart
lib/screens/profile_screen.dart
lib/utils/bottom_navbar_tabs.dart
lib/widgets/animated_nav_bar.dart
lib/widgets/bottom_navigation.dart
pubspec.lock

there is somethiing wrong with setstate so i used provider,

integration of pageview with navigationBar

---

lib/screens/classes_screen.dart
lib/widgets/animated_nav_bar.dart
lib/widgets/bottom_navigation.dart

hard coded calender removed with real calender with tap function so that user can select date of shedules class 3 days ahead and 3 days before of current date

Calender feature

---

lib/models/homework.dart
lib/widgets/recents_homeworks.dart

Fixes #32 
made a collection for homework and added a dummyCollege document
The homeworks are now connected to the backend.
Here is the DB
Here is the homework widget
Here is the homeworkPage
When the list is empty

Added backend to homework

---

lib/models/homework.dart
lib/screens/homework_screen.dart
lib/widgets/recents_homeworks.dart

Fixes #39 
Change the UI as desired
here is the ss

Issue#39 homework page UI

---

lib/screens/alert_screen.dart
lib/utils/bottom_navbar_tabs.dart
lib/widgets/bottom_navigation.dart

Added Alert Screen

---

lib/screens/home_screen.dart
lib/screens/onboarding_page.dart
lib/screens/welcome_screen.dart
lib/widgets/login_form.dart
lib/widgets/recents_homeworks.dart
lib/widgets/signup_form_additional_details.dart
lib/widgets/signup_form_essential_details.dart
pubspec.lock
pubspec.yaml

Replaced deprecated widgets (RaisedButtons, FlatButtons) and updated plugins versions in pubspec.lock so that app doesn't crash while building with flutter ^2.0.0. Let me know if any changes are required. Thanks.

For #55 Replaced deprecated widgets and updates plugins according to Flutter v2

---

lib/screens/profile_screen.dart
lib/services/authentication.dart
lib/services/user_db_services.dart
lib/widgets/login_form.dart
lib/widgets/signup_form_additional_details.dart
pubspec.lock

Sign-Up/ Log-In Email Verification Added..... Without Registered email verification, user can't log-in into the account.....
When User Complete sign up with email, password..... A verification email will send to the registered email.... Then User fill the signup form of additional details..... Then User Notify that, verification email send to the registered mail and verify email at first and then log in and user navigate to the log-in page..... Now user can't log-in Without email verification...... If the user not verify registered email by verification link, user can't log-in to the account....
Replace `#81` with the issue number which is fixed in this PR
<p>
</p>
Thanks a lot @avinashkranjan @HimeshNayak for assign me in that issue.... Hope you will review it and merged it soon.... If …

Sign-up Log-in Email Verification Added(#81)

---

lib/widgets/auth_input_form_field.dart
lib/widgets/signup_form_additional_details.dart

Keyboard Restriction Added for College Academic Year.... Now only number keyboard will show for college academic year
Replace ` #93 ` with the issue number which is fixed in this PR

Keyboard Restriction Added for College Academic Year

---

lib/constants.dart
lib/widgets/signup_form_additional_details.dart

Changed the college textfield in sign up page to a dropdown button which gets it's dropdown values from firebase's 'colleges' collection.

Changed college textfield to dropdown with dropdown values from firebase

---

lib/screens/home_screen.dart

Search Bar focused border added.

---

WikiPagesREADME.md

Added WIKI Pages
Replace #76 with the issue number which is fixed in this PR
Hope you review it @HimeshNayak  and merge it @avinashkranjan  soon

Wiki Pages Added as README File

---

android/app/src/main/AndroidManifest.xml
android/settings_aar.gradle
ios/Runner/Info.plist
lib/screens/profile_screen.dart
lib/services/user_db_services.dart
lib/services/user_info_services.dart
lib/widgets/header.dart
lib/widgets/signup_form_additional_details.dart
pubspec.lock
pubspec.yaml

Added image picker on profile screen to select image from gallery. The image gets updated on the home and profile screen and also the doc on firestore gets updated too.

Added image picker

---

lib/screens/profile_screen.dart
lib/services/authentication.dart
lib/widgets/header.dart
pubspec.lock
pubspec.yaml

Now user data gets fetched on first login which earlier wasn't happening.

Now user data gets fetched on first login

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
lib/screens/onboarding_page.dart
lib/screens/profile_screen.dart
lib/services/classes_db_services.dart
lib/widgets/signup_form_additional_details.dart
pubspec.lock
pubspec.yaml

What I Introduce/ Change:
1. If Colleges not in list, then user can manually add college name(Same for Courses and Department)
2. Proper Structurize data in firebase to fetch at the time of sign_up_form_additional_details
3. Profile Screen Error Solved(I have to do it due to work flexibility... That gives unexpected error)
4. Some small bugs fixed(Raise due to old plugin version)
Replace `#112` with the issue number which is fixed in this PR
<p>
</p>
Hope you will review it soon @HimeshNayak .... and will merge it soon @avinashkranjan

Dropdown for Courses, Stream Added with add data to firebase

---

lib/widgets/signup_form_additional_details.dart

Proper Age Validation Added in Sign-up form additional Details
Replace `#126` with the issue number which is fixed in this PR
I am also a GSSOC'21 participant....Please review it and merge it with add the required labels associated with that program and related isuue(#126)
Hope you review it and merge it soon @HimeshNayak @avinashkranjan

Proper Age Validation Added in Sign-up form additional Details

---

lib/screens/onboarding_page.dart

Landing page contents where overriding to each others, I have made entire screen responsive.
Replace #88  with the issue number which is fixed in this PR
Screenshot :

[Fixes] : Landing page content override

---

lib/screens/signup_additional_details_screen.dart
lib/services/facebookAuthentication.dart
lib/services/googleAuthentication.dart
lib/widgets/signup_form_additional_details.dart

Now After Google/FB Sign-in user navigate to `additional details` page and then `bottom navigation` page instead of `log-in` page
Replace `#128` with the issue number which is fixed in this PR
Not Possible to add screenshots because this is involved in navigation process...
Hope you review it and merge it soon @HimeshNayak @avinashkranjan

Now After Google/FB Sign-in user navigate to `additional details` page and then `bottom navigation` page instead of `log-in` page

---

lib/screens/signup_additional_details_screen.dart
lib/services/authentication.dart
lib/services/facebookAuthentication.dart
lib/services/googleAuthentication.dart
lib/services/user_db_services.dart
lib/widgets/signup_form_additional_details.dart

What I made Changes:-
1. Now After User SignUp, the user navigates to the `log-in` page instead of the `additional_details` page.
2. If User Log-in Successfully with Verification, then
2.1) If user data is present in firestore, they navigate to the `bottom_navigation` page.
2.2) If absent, Then User Switch to the `Sign-up-additional-details` page and then the `bottom_navigation` page.
3. On the `Sign-Up-Form-Additional-Details` page, I changed `Sign-up` heading to `Additional Details` and at the bottom, the `Sign Up` button to the `Save` button, as after log-in, take additional information with title and button named as `Sign Up` does not make a sense...
Replace `#134` with the issue number which is fixed in this PR
<p>
</p>
I am also a …

Now Firestore can't affect by Scammers

---

lib/screens/homework_screen.dart

FIX: HW page error Issue #139

---

lib/screens/profile_screen.dart
lib/utils/bottom_navbar_tabs.dart

Bottom navigation current Index was not resetting, I have added a provider reset function.
Replace #137  with the issue number which is fixed in this PR
Preview 
https://user-images.githubusercontent.com/55452299/114145747-62363180-9934-11eb-8f01-1593a3e202a3.mp4

[Fixes] : wrong bottom navigation on login

---

lib/screens/alert_screen.dart

FIX: AlertsPageError Issue #132

---

lib/models/users.dart
lib/screens/classes_screen.dart
lib/services/classes_db_services.dart
lib/widgets/build_classes.dart
pubspec.lock
pubspec.yaml

Change in classes UI. In this release, the calendar format is completely changed and classes are shown according to the date selected in the calendar.
I have added basic design and colors. Please let me know if you have anything specific in mind.

classes UI : table calendar format

---

lib/models/classes.dart
lib/models/users.dart
lib/screens/classes_screen.dart
lib/services/classes_db_services.dart
lib/widgets/build_classes.dart
lib/widgets/header.dart
lib/widgets/signup_form_additional_details.dart
pubspec.yaml

Feature Added:
1.  User Can Manually Add New Class.
2.  User can Add Classes for separate days.
3.  For Add new class, date automatically added.
4.  Some Coding Structure changed of that specific.
Fixed Feature:
1. Change the show class List With Stream as Fetch Real-Time Update.
2. Make Heading Some Comfortable with side pictures.
Replace `#145` with the issue number which is fixed in this PR
<p>
</p>
Hope you will review it soon @HimeshNayak and will merge it soon @avinashkranjan

Add New Class Manually by user with Separate Day

---

lib/widgets/signup_form_additional_details.dart

The overflow was in the dropdown button
the dropdown button has a property isExpanded which after it's made true it takes the entire only available space
so now the overflow issue is fixed

fixed overflow at signup page

---

README.md

@avinashkranjan I have added no.of forks,issues,pr's,stars and license,repo size in the bottom of readme file. Please check this pr for the issue #157 .
Before:
After:

Added no.of forks,issues,pr's and license,repo size

---

README.md

Errors in Documentation - Improve the README by adding some new sections and removing errors

---

lib/screens/home_screen.dart

FEAT: HomePage Search Error Issue #136

---

.github/ISSUE_TEMPLATE/bug_report.md

##Addresses #(165)  where necessary changes were to be  made

Updated Bug Report Template (#165)

---

README.md

I have improve and made changes in the logo of the project. This pr is under issue #56.
Replace `issue_no` with the issue number which is fixed in this PR

Updating the the logo of the project

---

lib/models/users.dart

The code has been updated to fix some issues and improve code readability. The changes include adding required parameters in the User constructor, handling nullable types properly, and ensuring the code follows standard naming conventions. The code has also been formatted for better readability.
[-] Yes
[ ] No
- [-] Bug fix (non-breaking change which fixes an issue)
- [-] My code follows the style guidelines(Clean Code) of this project
- [-] I have performed a self-review of my own code
- [-] My changes generate no new warnings

 Code Issues Resolved and Corrected

---

lib/widgets/countdown_painter.dart

modified: countdown_painter file 

---

lib/widgets/auth_input_form_field.dart

- Yes
- Bug fix 
- My code follows the style guidelines(Clean Code) of this project
- I have performed a self-review of my own code
- My changes generate no new warnings
- I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

modified: auth_input_form_field.dart file 

---

lib/widgets/signup_form_essential_details.dart

Made the required adjustments to ensure the updated code functions correctly.
-  Yes
- Bug fix (signup_form_essential_details.dart)

modified: signup_form_essential_details.dart

---

lib/services/facebookAuthentication.dart

Made the required adjustments to ensure the updated code functions correctly and also Null Safety Issues Leading to Compilation Errors (Fixed).
-  Yes
-  Bug fix 

modified: facebookAuthentication.dart file 

---

lib/models/alert.dart
lib/utils/bottom_navbar_tabs.dart
lib/widgets/onboarding_canvas_design.dart

Required changes modified in these files 
- lib/models/alert.dart
- lib/utils/bottom_navbar_tabs.dart
- lib/widgets/onboarding_canvas_design.dart
-  Yes
- Bug fix

Required changes modified

---

lib/screens/home_screen.dart

Made the required adjustments to ensure the updated code functions correctly and also Null Safety Issues Leading to Compilation Errors 
-  Yes
-  Bug fix 
- My code follows the style guidelines(Clean Code) of this project
- I have performed a self-review of my own code
- My changes generate no new warnings
- I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

modified: home_screen.dart file 

---

lib/screens/login_page.dart
lib/screens/signup_additional_details_screen.dart
lib/screens/signup_page.dart
lib/screens/splash.dart

Required changes modified in these files
- lib/screens/login_page.dart
- lib/screens/signup_additional_details_screen.dart
- lib/screens/signup_page.dart
- lib/screens/splash.dart
-  Yes
- Bug fix
- My code follows the style guidelines(Clean Code) of this project
- I have performed a self-review of my own code
- My changes generate no new warnings
- I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Required changes modified 

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/gradle/wrapper/gradle-wrapper.properties

Some changes required in these files - 
-  android/app/build.gradle
-  android/app/src/main/AndroidManifest.xml
-  android/gradle/wrapper/gradle-wrapper.properties
-  Yes
- Bug fix

Version Updated 

---

lib/widgets/round_button.dart

Required changes modified in round_button.dart file 
-  Yes
-  Bug fix 

widgets/round_button.dart file fixed 

---

lib/widgets/login_form.dart

Made the required adjustments to ensure the updated code functions correctly.
-  Yes
- Bug fix (login_form.dart)

modified: login_form.dart

---

lib/widgets/build_classes.dart

Code Issues Resolved

---

lib/widgets/bottom_navigation.dart

The code has been enhanced to address certain issues and enhance code readability. The enhancements encompass the addition of mandatory parameters, appropriate handling of nullable types, and improved code formatting for enhanced readability.
-  Yes
-  Bug fix

bottom_navigation.dart Errors resolved

---

lib/models/homework.dart

Made the required adjustments to ensure the updated code functions correctly and also Null Safety Issues Leading to Compilation Errors
-  Yes
-  Bug fix 

modified homework.dart file 

---

lib/widgets/animated_nav_bar.dart

Made the required adjustments to ensure the updated code functions correctly.
-  Yes
-  Bug fix (animated_nav_bar.dart)
-   My code follows the style guidelines(Clean Code) of this project
-   I have performed a self-review of my own code
-   My changes generate no new warnings
-   I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Modified: animated_nav_bar.dart file

---

lib/screens/profile_screen.dart

Enhancing the profile page user interface to ensure consistency and improve the overall user experience.
- Consistent Edit Functionality
- Streamlined Profile Picture Handling
- Clear Edit Button
-  Yes
-  All bugs are fixed 
-  Bug fix (non-breaking change which fixes an issue)
-  New feature (non-breaking change which adds functionality)
-  Breaking change (fix or feature that would cause existing functionality to not work as expected)

Enhancing profile_screen 

---

lib/services/googleAuthentication.dart

The necessary modifications have been made to the code, and the issues have been resolved.
-  Yes
- Bug fix

Modified: googleAuthentication.dart 

---

lib/screens/classes_screen.dart

Made the required adjustments to ensure the updated code functions correctly and also Null Safety Issues Leading to Compilation Errors
-  Yes
-  Bug fix 

modified: classes_screen.dart

---

lib/widgets/auth_handling_widget.dart

The necessary modifications have been made to the code, and the issues have been resolved.
- Yes
- Bug fix 

Modified: auth_handling_widget.dart 

---

lib/services/classes_db_services.dart

Made the required adjustments to ensure the updated code functions correctly and also Null Safety Issues Leading to Compilation Errors
-  Yes
-  Bug fix 

Modified: classes_db_services.dart

---

lib/widgets/recents_homeworks.dart

The necessary modifications have been made to the code, and the issues have been resolved.
Minor error in "return homeworkListBuilder(list.data);" 
-  Yes
-  Bug fix

recents_homeworks.dart file fixed 

---

lib/widgets/reset_password.dart

reset_password.dart file fixed

---

README.md

Add the logo of the project before the name of it and fixed some typos. #270
Replace `issue_no` with the issue number which is fixed in this PR
- [x
] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

Improvements in README.md #270

---

lib/services/authentication.dart

authentication.dart file fixed 

---

lib/screens/loading_screen.dart

The necessary modifications have been made to the code, and the issues have been resolved.
-  Yes
-  Bug fix 

loading_screen.dart file fixed

---

lib/services/user_info_services.dart

The code has been updated to fix issues and improve code readability.
-  Yes
-  Bug fix 
- User class added 

Modified: user_info_services.dart

---

lib/widgets/bottom_navigation.dart

Update for BottomNavigation file
-  Yes
- Bug fix
- Added the required 'key' parameter to the 'BottomNavBar' widget.
- Replaced the usage of the deprecated 'backgroundColor' property with 'colorScheme.background'.

Updated bottom_navigation.dart file

---

lib/screens/loading_screen.dart

Error Fixed 
- Loading_screen.dart file
-  Yes
-  Bug fix 

Loading screen error fixed 

---

pubspec.lock
pubspec.yaml

While debugging the code, I encountered errors in certain files. The reason behind these errors was that some necessary Flutter packages were not included within the file that was causing the problem.
like - 
- introduction_screen: ^3.1.9
- is_first_run: ^1.0.0
- shared_preferences: ^2.1.1
Now it is working perfectly fine 
-  Yes
-  Bug fix 
- Missing dependencies in pubspec.yaml (added in this pull request)

Code issues resolved 

---

.github/workflows/lint.yml

I have created a new Github action Workflow which Check format of code means Pretier and workflow code is added into  : `.github/workflows`

Feature - Added: Created Workflow for Code Formatting ⚡

---

lib/models/users.dart
lib/screens/profile_screen.dart
lib/services/user_db_services.dart

The bio feature is implemented as a text field within the user's profile. When the ProfileScreen is loaded, the user's bio is retrieved from the database or storage and displayed in a "buildDetails" widget.
The bio feature in a classroom application is essential for users to introduce themselves, personalize the learning experience, foster a sense of identity and belonging, and create a supportive classroom community. It enhances connections, promotes engagement, and contributes to a more effective educational experience overall.
-  Yes
-  New feature 
-  I have added tests/screenshots(if any) that prove my fix is effective or that my …

Bio feature added 

---

lib/main.dart
lib/screens/app_info_screen.dart
lib/screens/contact_us_screen.dart
lib/screens/help_screen.dart
lib/screens/settings_screen.dart

In the Help screen, I have added the following feature:
**Contact Us Feature:**
- To enhance user support and communication, I included a Contact Us feature in the Help screen.
- Users can access this feature by navigating to the Help screen from the app's navigation menu.
- Within the Help screen, there is a "Contact Us" button that users can tap to initiate contact with the support team.
- When the "Contact Us" button is pressed, the app navigates to the Contact Us screen, where users can find contact information such as email and phone number.
- The Contact Us screen provides users with a convenient way to seek assistance, report issues, or provide feedback to the app's support team.
**App Info Feature:**
- Within the Help screen, I have added an "App Info" button that provides users …

New features added in Help screen

---

Dockerfile
android/.settings/org.eclipse.buildship.core.prefs
android/gradle/wrapper/gradle-wrapper.properties

Replace `issue_no` with the issue number which is fixed in this PR

Docker file is added

---

lib/main.dart
lib/onboarding/introslider.dart
lib/screens/favourites_screen.dart
lib/screens/home_screen.dart
lib/widgets/recents_alerts.dart
lib/widgets/signup_form_additional_details.dart
pubspec.lock
pubspec.yaml

For #320, 
I've added te favourites section where the user can see their favourite or most important exams/assessment details. The implementation is such that it would not require internet data or any additional user model, and extracts favourited assessments/exams right from the "Alerts" modal class. 
Sample video of the implementation: [See video of favourites section](https://drive.google.com/file/d/1MVmqACH9IvGwwRuCbBzYSxZ4Ao1Z81g8/view?usp=sharing)
For #319,
I've fixed the error in signup_forms_additional_details.dart file. This makes the application's user sign up process exception free. 

added "Favourites" section and fixed the issue 319

---

pubspec.lock
pubspec.yaml

dependencies added

---

README.md

README.md File improved
-  Yes
-  Bug fix 

README.md File improved

---

lib/screens/chat_screen.dart
lib/screens/home_screen.dart
lib/screens/new_group_screen.dart
lib/services/chats_db.dart

The latest update introduces a floating action button prominently placed on the home page at the bottom right corner. This button serves as a convenient entry point for accessing the chat functionality.
When you tap on the floating action button, a new page titled "Chats" opens, providing a dedicated space for managing your conversations. The chat screen offers a streamlined interface, allowing you to navigate and interact with your chats seamlessly.
Within the chat screen, we have introduced a new feature called "New Groups," designed to empower users to create and manage group conversations effortlessly. This feature can be accessed by tapping on a dedicated row titled "New Groups." By leveraging the power of group chats, you can collaborate and connect with multiple individuals at …

Chat Feature added

---

lib/main.dart
lib/screens/onboarding_page.dart
lib/screens/phone_verification_screen.dart
lib/screens/verify_code_screen.dart
lib/services/phone_number_verification_db.dart

This pull request introduces a new feature to the existing sign-up process in our application - Phone Verification. This enhancement adds an extra layer of security and ensures the validity of user phone numbers during registration.
**Key Changes:**
- Added a new screen: PhoneVerificationScreen - This screen allows users to enter their mobile number and initiates the phone verification process.
- Added a new screen: VerifyCodeScreen - This screen prompts users to enter the verification code received on their mobile devices and verifies it against the provided phone number.
- Created a PhoneNumberVerificationDb class - This class handles the verification process using Firebase Authentication's phone number verification functionality.
Made necessary imports and dependencies for the new …

Adding Phone Verification Feature to Sign Up Process

---

.github/workflows/issue-assign.yml

The Auto Issue Assignment feature is designed to automate the assignment of issues in a GitHub repository based on specific criteria. By leveraging GitHub Actions, this feature enables the automatic assignment of issues to users who meet predefined conditions, streamlining the issue management process and ensuring prompt attention to problems or tasks.
**Screen Shot -**
-  Yes
-  New feature

Auto assign feature

---

lib/main.dart
lib/screens/faqs_screen.dart
lib/screens/settings_screen.dart

The Frequently Asked Questions (FAQ) feature provides users with quick answers to common queries and concerns related to the assignment reminder app. It offers a convenient way for students to find solutions to their questions without the need for direct assistance. 
The FAQ screen presents a list of questions, each expandable to reveal a detailed answer. Users can easily navigate through the FAQ items and access relevant information to resolve their doubts. 
**Demo Video -**
https://github.com/avinashkranjan/Friday/assets/121665385/7fce6ebe-d8b4-4603-be7c-c298191b444b
-  Yes
-  New feature 
-  I have added tests/screenshots(if any) …

FAQ Feature added

---

lib/main.dart
lib/screens/settings_screen.dart
lib/screens/theme_screen.dart
lib/screens/themes.dart

One of the key features of the app is the ability to switch between different themes - light and dark themes. The theme feature enhances the user experience by allowing them to personalize the app's appearance according to their preferences.
Light Theme:
The light theme provides a clean and bright look to the app interface. It uses a light color palette with a white or light background and darker text. This theme is suitable for well-lit environments or users who prefer a more vibrant and energetic visual style.
Dark Theme:
The dark theme offers a visually striking and modern interface. It utilizes a dark background with lighter text and accent colors, reducing eye strain in low-light conditions. This theme is ideal for users who prefer a more subdued and immersive experience, …

Theme feature added 

---

README.md

Changed the current image to images which will load based on device theme
Screenshots - 

Dynamic GSSOC banner 

---

lib/screens/home_screen.dart
pubspec.lock
pubspec.yaml

The Assignment Progress Chart is a new feature added to the Home Screen of the app. It allows users to track their assignment progress visually through a chart representation. The chart displays the scores of completed assignments over time, helping users to monitor their performance and identify trends.
Here is the demo Screenshot - 
The chart is placed within the Home Screen, providing users with a comprehensive overview of their recent alerts and homework, along with the visual representation of their assignment progress. The feature enhances the user experience by providing an intuitive and engaging way to track progress.
Additionally, the feature includes labels for the horizontal and vertical lines in the chart. The horizontal line is labeled as "Progress Line" to indicate the trend …

Progress Graph added

---

.github/workflows/release.yml

created Github Workflow which is automatically Generates Changelog for Project 
Replace `issue_no` with the issue number which is fixed in this PR

feat: ⚙️ GitHub repo configs added

---

lib/screens/contact_us_screen.dart
lib/screens/faqs_screen.dart
lib/screens/help_screen.dart

The UI of "Help" and "FAQ" sections were primitie ones and lacked coherance with the rest of the application. I've changed the overall design and look of the page so that they become in-sync with the rest of the application. 

changed UI of help and FAQ sections

---

lib/screens/contact_us_screen.dart
pubspec.lock
pubspec.yaml

I've implemented the google sheetds API to push the user queries data filled by the user from the ```contact us``` page to the Google sheet. From this sheet, whatever queries posted by the users, along with their email and their timestamp of posting would be displayed in this sheet. 
Sheet link: https://docs.google.com/spreadsheets/d/14ewMrJbsoadMUTvUEEVffVBh1KqrEy0wZ_MrAtdYU_A/edit?usp=sharing
This API has been created by using the ```scripts``` feature of google sheets, where i created the relevant functions and deployed them for use. The sheet is open for anyone currently. The steps for making it private to Friday application owners are as follows:
- Open the sheet in the owner's Google account.
- Then, open the scripts module from ```Extension``` -> ```App Script```. 
- Create new …

Adding API for sending user queries through contact us page

---

lib/screens/app_info_screen.dart
lib/widgets/build_classes.dart

For #369,
I've changed the UI of the App info screen to match with the app's UI, as shown: 
For #370,
I've resolved the error associated with the ```build_classes.dart``` screen which was causing the calender to not to appear in the UI. 

Changed UI of App Ingo screen and resolved bugs

---

lib/widgets/build_classes.dart

I've updated the UI of the Calender widget such that each of it's components are clearly visible to the users, while also matching with the rest of the UI of the application. 

Resolved non-visible UI components in Calender table in BuildClasses screen

---

lib/screens/favourites_screen.dart
lib/screens/home_screen.dart
lib/widgets/recents_alerts.dart
pubspec.lock

I've added the ```mark all as unfavourite``` feature, along with implementing the **Flutter Binding** in Home Screen and Recent alerts classes. Clicking on this button removes all the favourites from the favourite section. And because of flutter binding, this gets updated in the home screen and recent alerts screen. 

added mark all as unfavourite option

---

lib/main.dart
lib/screens/home_screen.dart
lib/screens/settings_screen.dart
lib/widgets/build_classes.dart
lib/widgets/recents_alerts.dart

Added the option to change the language from the settings section of the application. Through this, the user would be able to change from one locale to another.

Added Change Language option in Settings

---

lib/main.dart
lib/screens/settings_screen.dart

I've modified the ontap() function of support development option to make it function.

Resolved: Support development option now functioning.

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

Updated titles of Issue templates according to the latest docs

fix: Updated titles according to the latest docs

---

README.md

- Added admins all 3 social links
- Added gssoc link in the open source projects section

fix: Added gssoc & admin social handles links

---

lib/screens/themes.dart

I've changed the color and UI of light mode to make the texts and alerts look clear and match with the rest of the UI.

Updated the color schema and UI of light mode

---

lib/main.dart
lib/screens/settings_screen.dart
lib/screens/themes.dart
lib/services/theme_provider.dart

I've added changes to the light theme and dark theme UI implementation and ensured that it functions.

Added Light theme in app
